version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: '04:00'
  open-pull-requests-limit: 10
  target-branch: master
  labels:
  - dep:javascript
  - dependencies
- package-ecosystem: npm
  directory: "/bots/twitch"
  schedule:
    interval: monthly
    time: '04:00'
  open-pull-requests-limit: 10
  target-branch: master
  labels:
    - dep:javascript
    - dependencies
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: '04:00'
  open-pull-requests-limit: 10
  target-branch: master
  labels:
  - dependencies
  - dep:php
