version: '3.7'

  ### ElasticSearch ########################################

  elasticsearch:
    image: abenevaut/laradock-elasticsearch:0.1.2
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "${SCOUT_ELASTIC_PORT}:9200"
      - "${DOCKER_ELASTICSEARCH_PUBLIC_NODE_PORT}:9300"
    depends_on:
      - php-fpm
    networks:
      - frontend
      - backend

  ### Kibana ##############################################

  kibana:
    image: abenevaut/laradock-kibana:0.1.2
    ports:
      - "${DOCKER_KIBANA_PUBLIC_PORT}:5601"
    depends_on:
      - elasticsearch
    networks:
      - frontend
      - backend
